#!/usr/bin/env python3
"""
Generate site_ui/_config.local.yml from a local .env.local file.

Usage:
    python scripts/gen_local_config.py [--env PATH] [--out PATH]

Defaults:
    --env: site_ui/.env.local (fallback: .env.local)
    --out: site_ui/_config.local.yml
"""

import os
import sys
import argparse
from pathlib import Path


def parse_env_file(filepath: Path) -> dict:
    """Parse a simple .env file into a dictionary of string key-values."""
    env_vars = {}
    if not filepath.exists():
        return env_vars

    with open(filepath, "r", encoding="utf-8") as f:
        for line_no, raw_line in enumerate(f, start=1):
            line = raw_line.strip()
            # Skip comments and empty lines
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            
            key, val = line.split("=", 1)
            key = key.strip()
            val = val.strip()

            # Strip surrounding quotes if present
            if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                val = val[1:-1]

            env_vars[key] = val

    return env_vars


def generate_local_config(env_vars: dict, output_path: Path):
    """Generate the Jekyll YAML override configuration file."""
    api_url = env_vars.get("API_URL", "PLACEHOLDER_API_URL")
    cognito_region = env_vars.get("COGNITO_REGION", "us-east-1")
    cognito_client_id = env_vars.get("COGNITO_CLIENT_ID", "PLACEHOLDER_COGNITO_CLIENT_ID")
    cognito_user_pool_id = env_vars.get("COGNITO_USER_POOL_ID", "PLACEHOLDER_COGNITO_USER_POOL_ID")
    baseurl = env_vars.get("BASEURL", "")
    url = env_vars.get("URL", "http://localhost:4000")

    yaml_content = f"""# Auto-generated by scripts/gen_local_config.py
# DO NOT COMMIT THIS FILE TO GIT.
baseurl: "{baseurl}"
url: "{url}"
api_url: "{api_url}"
cognito_region: "{cognito_region}"
cognito_client_id: "{cognito_client_id}"
cognito_user_pool_id: "{cognito_user_pool_id}"
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(yaml_content)


def main():
    parser = argparse.ArgumentParser(description="Generate _config.local.yml from .env.local")
    parser.add_argument("--env", type=str, default=None, help="Path to .env.local file")
    parser.add_argument("--out", type=str, default=None, help="Path to output _config.local.yml")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent

    # Locate input env file
    if args.env:
        env_path = Path(args.env).resolve()
    else:
        site_env = repo_root / "site_ui" / ".env.local"
        root_env = repo_root / ".env.local"
        env_path = site_env if site_env.exists() else root_env

    # Locate output config file
    if args.out:
        out_path = Path(args.out).resolve()
    else:
        out_path = repo_root / "site_ui" / "_config.local.yml"

    if not env_path.exists():
        print(f"[!] Warning: No .env.local file found at {env_path}")
        print(f"    You can create one by copying site_ui/.env.local.example:")
        print(f"    cp site_ui/.env.local.example site_ui/.env.local")
        sys.exit(1)

    print(f"[*] Reading environment from: {env_path}")
    env_vars = parse_env_file(env_path)

    generate_local_config(env_vars, out_path)
    print(f"[+] Generated local Jekyll config at: {out_path}")
    print("\nNext step: Run Jekyll locally:")
    print("  cd site_ui")
    print("  bundle exec jekyll serve --config _config.yml,_config.local.yml\n")


if __name__ == "__main__":
    main()
