title: BG Recommender
description: A simple Jekyll site.
baseurl: "/Boardgame-Recommender"
api_url: "PLACEHOLDER_API_URL"
cognito_region: "us-east-1"
cognito_client_id: "PLACEHOLDER_COGNITO_CLIENT_ID"
cognito_user_pool_id: "PLACEHOLDER_COGNITO_USER_POOL_ID"



