name: BGG Game Scraper Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - bgg_game_scraper/**
      - ".github/workflows/scraper-docker-image.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - bgg_game_scraper/**
      - ".github/workflows/scraper-docker-image.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
      run: docker build . --file Dockerfile --tag bgg_scraper:$(date +%s)
      working-directory: ./bgg_game_scraper
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Get ECR URL
      run: echo "ECR_URL=$(aws secretsmanager get-secret-value --region us-east-1--secret-id ecr_repository_url --query SecretString --output text)" >> $GITHUB_ENV
    - name: Push the Docker image to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_URL}
        docker tag bgg_scraper:$(date +%s) ${ECR_URL}:latest
        docker push ${ECR_URL}:latest
      working-directory: ./bgg_game_scraper

