name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - ./bgg_game_scraper/
  pull_request:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./bgg_game_scraper/ --file Dockerfile --tag bgg_scraper:$(date +%s)
