name: 'Terraform'

on:
  push:
    branches: [ "main" ]
    paths:
      - infrastructure/**
      - ".github/workflows/terraform.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - infrastructure/**
      - ".github/workflows/terraform.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: lambda
    env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        TF_VAR_S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME_SCRAPER}}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend-config=config.s3.tfbackend
      working-directory: ./infrastructure

    # Checks that all Terraform configuration files are syntactically valid and internally consistent, regardless of any state or variables
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infrastructure

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./infrastructure

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false
      working-directory: ./infrastructure
  
  lambda:
    name: 'Build Lambda Zip'
    runs-on: ubuntu-latest
    steps:
      - name: Build Lambda Zip
        run: |
          mkdir -p package
          pip install -r requirements.txt -t ./package
          cd package
          zip -r ../bgg_game_data_scraper.zip .
          cd ..
          zip -g bgg_game_data_scraper.zip bgg_game_data_scraper.py
          mv bgg_game_data_scraper.zip ../infrastructure/bgg_game_data_scraper.zip
        working-directory: bgg_game_data_scraper/

